# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 801, 471))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.AllObj = QtWidgets.QWidget()
        self.AllObj.setObjectName("AllObj")
        self.tabWidget.addTab(self.AllObj, "")
        self.Obj_br = QtWidgets.QWidget()
        self.Obj_br.setObjectName("Obj_br")
        self.tabWidget.addTab(self.Obj_br, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRegister_User = QtWidgets.QAction(MainWindow)
        self.actionRegister_User.setObjectName("actionRegister_User")
        self.actionRegister_Object = QtWidgets.QAction(MainWindow)
        self.actionRegister_Object.setObjectName("actionRegister_Object")
        self.actionClose_Program = QtWidgets.QAction(MainWindow)
        self.actionClose_Program.setObjectName("actionClose_Program")
        self.actionCreate_User_in_store = QtWidgets.QAction(MainWindow)
        self.actionCreate_User_in_store.setObjectName("actionCreate_User_in_store")
        self.menuMenu.addAction(self.actionRegister_User)
        self.menuMenu.addAction(self.actionRegister_Object)
        self.menuMenu.addAction(self.actionCreate_User_in_store)
        self.menuMenu.addAction(self.actionClose_Program)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AllObj), _translate("MainWindow", "รายการวัสดุทั้งหมด"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Obj_br), _translate("MainWindow", "รายการวัสดุที่ถูกยืม"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "รายชื่อผู้ใช้งานในระบบ"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionRegister_User.setText(_translate("MainWindow", "Register User"))
        self.actionRegister_Object.setText(_translate("MainWindow", "Register Object"))
        self.actionClose_Program.setText(_translate("MainWindow", "Close Program"))
        self.actionCreate_User_in_store.setText(_translate("MainWindow", "Create User in store"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
